version: 0.2
env:
    variables:
        S3_BUCKET: "{{github-s3-angular-bucket}}"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-version:
      nodejs: 14.17.6
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli@12.2.4
  build:
    commands:
      - echo Build started
      - ng build
